CREATE TABLE students (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_number INT UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE NOT NULL,
	email VARCHAR(100),
    status VARCHAR(10)
        CHECK (status IN ('active', 'inactive', 'graduated'))
        NOT NULL
);

CREATE TABLE courses (
    course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(10) UNIQUE NOT NULL,
    course_name VARCHAR(50) NOT NULL,
    credits DECIMAL(3,1) NOT NULL,
    status VARCHAR(10)
        CHECK (status IN ('active', 'inactive'))
        NOT NULL
);

CREATE TABLE enrollments (
    enrollment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    academic_year VARCHAR(9) NOT NULL,
    term CHAR(1)
        CHECK (term IN ('1', '2'))
        NOT NULL,
    enrollment_date DATE NOT NULL,

    CONSTRAINT fk_student
        FOREIGN KEY (student_id)
        REFERENCES students(student_id),
    CONSTRAINT fk_course
        FOREIGN KEY (course_id)
        REFERENCES courses(course_id),

	CONSTRAINT unique_enrollment_per_term
        UNIQUE (student_id, course_id, academic_year, term)
);

CREATE TABLE grades (
    grades_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INT NOT NULL,
    grade_type VARCHAR(15)
        CHECK (grade_type IN ('test', 'assignment', 'exam'))
        NOT NULL,
    grade_value INT
        CHECK (grade_value BETWEEN 0 AND 100),
    grade_date DATE NOT NULL,

    CONSTRAINT fk_enrollment_grade
        FOREIGN KEY (enrollment_id)
        REFERENCES enrollments(enrollment_id)
);

CREATE TABLE attendance (
    attendance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INT NOT NULL,
    attendance_date TIMESTAMP NOT NULL,
    status VARCHAR(10)
        CHECK (status IN ('present', 'absent', 'late'))
        NOT NULL,

    CONSTRAINT fk_enrollment_attendance
        FOREIGN KEY (enrollment_id)
        REFERENCES enrollments(enrollment_id)
);
